# Brazil - No Show Appointment - Deu Migué <a id='topo'></a>

## Table of Contents
<ul>
<li>
    <a href="#intro">Introduction</a>
    <ul>
        <li><a href="#columns">Columns descriptions and insights</a></li>
    </ul>
</li>
<li>
    <a href="#wrangling">Data Wrangling</a>
    <ul>
        <li><a href="#general">General Properties</a></li>
        <li><a href="#check_unique">Check unique values</a></li>
        <li><a href="#check_date">Check the date fields</a></li>
        <ul>
            <li><a href="#convert_date">Convert to datetime</a></li>
            <li><a href="#check_schecule_appointment">Check if ScheduledDay > AppointmentDay</a></li>
            <li><a href="#clean_schedule">Clean ScheduledDay >= AppointmentDay</a></li>
        </ul>
        <li><a href="#check_appointment">Check AppointmentID</a></li>
        <li><a href="#check_patient">Check PatientId</a></li>
    </ul>
</li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

<a id='intro'></a>
## Introduction

This dataset collects information from 100k medical appointments in Brazil and is focused on the question of whether or not patients show up for their appointment. A number of characteristics about the patient are included in each row.

You can download the dataset [here](https://d17h27t6h515a5.cloudfront.net/topher/2017/October/59dd2e9a_noshowappointments-kagglev2-may-2016/noshowappointments-kagglev2-may-2016.csv). Put the file in same directory of this file and rename it to 'brasil_migue.csv'.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('brasil_migue.csv')

In [4]:
df.head(4)

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No

## Columns descriptions and insights <a id='columns'></a>

The columns that is not listed below are considered self explained.
- **Scholarship** - Indicates whether or not the patient is enrolled in Brasilian welfare program Bolsa Família. 
    - Could indicate the real scholarship of the patient. The information if the patition is in the welfare could be another column.
    
- **ScheduledDay** - The day that the patient set up their appointment. 
    - In the first lines listed above is possible to see some problems in this data, some dates are the same or after the appointment day. The same day is a problem because in brazilian public hospiltals an appointment is scheduled only months before. This data does not seem truthful.

- **Neighbourhood** - The place where the hospital is located and not where the patient lives.
    - A data set with informations about the region could be useful. Only the the name of the place, where the hospital is located, become diffcult to link the place with the reason that the patient does not show up. The location where the patient live could be useful because some hospitals receive patients from another cities.

- **Handcap** - I am considering that the handicap means people with disabilities.

- **No-show** - Yes if the patient does not show up.
    - I could invert the data to mean that the 'yes' may be when the patient showed up. The columns name could be showed up in this case. This could avoid misunderstood.
    
- **SMS_received** - If the patient received a sms remembering about the appointment.
    - I have doubts about if this data is relevant. There is some reasons about my doubts that I am going to try to explain below:
        - This system of reminder is not common in Brazil
        - Some patients are enrolled in the welfare program Bolsa Família. Most certain that they do not have cellphones. This can be cheked more later in the data analysis.
        - The data do not explain when the sms was received.

> **Note**: The insights above are only my first impressions about the data. I am goint to do a more profund analise later in this document.  

<a id='wrangling'></a>
## Data Wrangling

> **Tip**: In this section of the report, you will load in the data, check for cleanliness, and then trim and clean your dataset for analysis. Make sure that you document your steps carefully and justify your cleaning decisions.

### General Properties <a id='general'></a>

Display all the info about the data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
PatientId         110527 non-null float64
AppointmentID     110527 non-null int64
Gender            110527 non-null object
ScheduledDay      110527 non-null object
AppointmentDay    110527 non-null object
Age               110527 non-null int64
Neighbourhood     110527 non-null object
Scholarship       110527 non-null int64
Hipertension      110527 non-null int64
Diabetes          110527 non-null int64
Alcoholism        110527 non-null int64
Handcap           110527 non-null int64
SMS_received      110527 non-null int64
No-show           110527 non-null object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


There is no mising values in the data frame. Let's check if has duplicates values

In [8]:
sum(df.duplicated())

0

### Check unique values <a id='check_unique'></a>

In [9]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [10]:
df.Scholarship.unique()

array([0, 1], dtype=int64)

In [11]:
df.Hipertension.unique()

array([1, 0], dtype=int64)

In [12]:
df.Diabetes.unique()

array([0, 1], dtype=int64)

In [13]:
df.Alcoholism.unique()

array([0, 1], dtype=int64)

In [14]:
df.Handcap.unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [15]:
df.SMS_received.unique()

array([0, 1], dtype=int64)

In [17]:
df['No-show'].unique()

array(['No', 'Yes'], dtype=object)

According with the data set documentation, the Handcap column should be true or false. Futhermore, I am going to check if this data has some correlation with the patients that do not show up.

### Check the date fields <a id='check_date'></a>

First, let's convert to datetime the scheduled day and appointment day column

#### Convert to datetime <a id='convert_date'></a>
<a href='#topo'>Top</a>

In [4]:
df.ScheduledDay = pd.to_datetime(df.ScheduledDay)
df.AppointmentDay = pd.to_datetime(df.AppointmentDay)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
PatientId         110527 non-null float64
AppointmentID     110527 non-null int64
Gender            110527 non-null object
ScheduledDay      110527 non-null datetime64[ns]
AppointmentDay    110527 non-null datetime64[ns]
Age               110527 non-null int64
Neighbourhood     110527 non-null object
Scholarship       110527 non-null int64
Hipertension      110527 non-null int64
Diabetes          110527 non-null int64
Alcoholism        110527 non-null int64
Handcap           110527 non-null int64
SMS_received      110527 non-null int64
No-show           110527 non-null object
dtypes: datetime64[ns](2), float64(1), int64(8), object(3)
memory usage: 11.8+ MB


Now, I want to check how many Scheduled days are after the AppointmentDay

#### Check if ScheduledDay > AppointmentDay <a id='check_schecule_appointment'></a>
<a href='#topo'>Top</a>

In [7]:
df.query('ScheduledDay > AppointmentDay')

PatientId  AppointmentID Gender        ScheduledDay AppointmentDay  \
0       2.987250e+13        5642903      F 2016-04-29 18:38:08     2016-04-29   
1       5.589978e+14        5642503      M 2016-04-29 16:08:27     2016-04-29   
2       4.262962e+12        5642549      F 2016-04-29 16:19:04     2016-04-29   
3       8.679512e+11        5642828      F 2016-04-29 17:29:31     2016-04-29   
4       8.841186e+12        5642494      F 2016-04-29 16:07:23     2016-04-29   
8       5.639473e+13        5638447      F 2016-04-29 08:02:16     2016-04-29   
19      7.223289e+12        5640433      F 2016-04-29 10:43:14     2016-04-29   
24      8.734858e+12        5641780      F 2016-04-29 14:19:19     2016-04-29   
26      2.578785e+10        5641781      F 2016-04-29 14:19:42     2016-04-29   
28      5.926172e+12        5642400      M 2016-04-29 15:48:02     2016-04-29   
29      1.225776e+12        5642186      F 2016-04-29 15:16:29     2016-04-29   
32      5.288356e+13        5637908      M 2016-04-29 07:30:27     2016-04-29   
34      1.999976e+13        5637963      F 2016-04-29 07:34:30     2016-04-29   
35      7.816264e+13        5637968      M 2016-04-29 07:34:42     2016-04-29   
36      7.298459e+13        5637975      F 2016-04-29 07:35:19     2016-04-29   
37      1.578132e+12        5637986      F 2016-04-29 07:35:56     2016-04-29   
39      1.455623e+13        5639644      F 2016-04-29 09:21:13     2016-04-29   
43      7.155896e+13        5641620      F 2016-04-29 14:02:16     2016-04-29   
53      4.438587e+14        5637909      M 2016-04-29 07:30:31     2016-04-29   
54      3.371889e+12        5638164      F 2016-04-29 07:46:08     2016-04-29   
55      4.179932e+13        5638018      M 2016-04-29 07:37:45     2016-04-29   
57      3.996740e+12        5638466      M 2016-04-29 08:03:51     2016-04-29   
58      4.487944e+10        5638235      M 2016-04-29 07:50:15     2016-04-29   
59      7.184428e+13        5638545      F 2016-04-29 08:08:43     2016-04-29   
66      9.784893e+14        5638604      M 2016-04-29 08:12:27     2016-04-29   
67      8.647128e+13        5639264      F 2016-04-29 08:53:02     2016-04-29   
72      7.746486e+12        5638014      F 2016-04-29 07:37:37     2016-04-29   
77      5.753721e+12        5642767      F 2016-04-29 17:06:27     2016-04-29   
82      1.827125e+11        5638939      M 2016-04-29 08:36:19     2016-04-29   
83      2.274979e+11        5637742      M 2016-04-29 07:20:46     2016-04-29   
...              ...            ...    ...                 ...            ...   
110475  2.123885e+14        5779726      F 2016-06-07 07:14:07     2016-06-07   
110483  1.642781e+12        5769404      F 2016-06-03 08:47:58     2016-06-03   
110486  3.184153e+14        5788099      F 2016-06-08 11:14:23     2016-06-08   
110487  1.891645e+12        5786423      M 2016-06-08 08:24:51     2016-06-08   
110488  7.935892e+14        5760379      M 2016-06-01 14:47:12     2016-06-01   
110489  7.874370e+14        5788924      F 2016-06-08 13:54:16     2016-06-08   
110490  3.252624e+14        5787975      M 2016-06-08 10:55:45     2016-06-08   
110491  7.565622e+11        5787950      F 2016-06-08 10:52:27     2016-06-08   
110492  6.456342e+14        5786741      M 2016-06-08 08:50:19     2016-06-08   
110493  1.712135e+11        5788054      M 2016-06-08 11:06:40     2016-06-08   
110495  7.499489e+12        5759838      M 2016-06-01 13:49:47     2016-06-01   
110497  7.935892e+14        5757745      M 2016-06-01 09:46:33     2016-06-01   
110498  9.433654e+13        5787655      F 2016-06-08 10:21:14     2016-06-08   
110499  8.219692e+14        5757697      F 2016-06-01 09:42:56     2016-06-01   
110500  4.434384e+14        5787233      F 2016-06-08 09:35:13     2016-06-08   
110501  4.544252e+11        5758133      M 2016-06-01 10:19:12     2016-06-01   
110502  7.316229e+14        5787937      F 2016-06-08 10:50:42     2016-06-08   
110503  2.362182e+13        5759473      F

In [8]:
sum(df.ScheduledDay > df.AppointmentDay)

38568

In [9]:
sum(df.ScheduledDay == df.AppointmentDay)

0

I want to check if some patient in the results above received a sms

In [10]:
df.query('ScheduledDay > AppointmentDay and SMS_received == 1').SMS_received.count()

0

I am going to check if Appointment Day column has some value with time

In [11]:
sum(df.AppointmentDay.apply(lambda x: x.hour + x.minute + x.second + x.microsecond))

0

The column Appointment Day does not have time. I am going to check if has scheduled day value after the appointment day

In [12]:
different_day_array = []
for index, row in df.query('ScheduledDay > AppointmentDay').iterrows():
    if row['ScheduledDay'].day != row['AppointmentDay'].day:
        different_day_array.append(index)

In [13]:
df.loc[different_day_array].head()

PatientId  AppointmentID Gender        ScheduledDay AppointmentDay  \
27033  7.839273e+12        5679978      M 2016-05-10 10:51:53     2016-05-09   
55226  7.896294e+12        5715660      F 2016-05-18 14:50:41     2016-05-17   
64175  2.425226e+13        5664962      F 2016-05-05 13:43:58     2016-05-04   
71533  9.982316e+14        5686628      F 2016-05-11 13:49:20     2016-05-05   
72362  3.787482e+12        5655637      M 2016-05-04 06:50:57     2016-05-03   

       Age  Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
27033   38    RESISTÊNCIA            0             0         0           0   
55226   19  SANTO ANTÔNIO            0             0         0           0   
64175   22     CONSOLAÇÃO            0             0         0           0   
71533   81  SANTO ANTÔNIO            0             0         0           0   
72362    7     TABUAZEIRO            0             0         0           0   

       Handcap  SMS_received No-show  
27033        1             0     Yes  
55226        1             0     Yes  
64175        0             0     Yes  
71533        0             0     Yes  
72362        0             0     Yes

The dataset has values with scheduled day after the appointment day. I am going to remove these data.
The appointment values does not have time, so the appointment date in the same day of scheduled date could be after the schedule. But in Brazil there is no possible that the scheduled and appointment day be the same, so I am going to remove the rows that contains schedule equal or after the appointment.

#### Clean ScheduledDay >= AppointmentDay <a id='clean_schedule'></a>
<a href='#topo'>Top</a>

In [6]:
df = df.query('ScheduledDay < AppointmentDay')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71959 entries, 5 to 110526
Data columns (total 14 columns):
PatientId         71959 non-null float64
AppointmentID     71959 non-null int64
Gender            71959 non-null object
ScheduledDay      71959 non-null datetime64[ns]
AppointmentDay    71959 non-null datetime64[ns]
Age               71959 non-null int64
Neighbourhood     71959 non-null object
Scholarship       71959 non-null int64
Hipertension      71959 non-null int64
Diabetes          71959 non-null int64
Alcoholism        71959 non-null int64
Handcap           71959 non-null int64
SMS_received      71959 non-null int64
No-show           71959 non-null object
dtypes: datetime64[ns](2), float64(1), int64(8), object(3)
memory usage: 8.2+ MB


### Check AppointmentID <a id='check_appointment'></a>
Beforehand, I am goind to check if the data has Appointment id duplicated. <a href='#topo'>Top</a>

In [8]:
df.AppointmentID.duplicated().sum()

0

### Check PatientId <a id='check_patient'></a>
Maybe the patient can have more than one appointment. Let's check. <a href='#topo'>Top</a>

In [9]:
# Must be true to has more than one appointment
len(df.PatientId.unique()) != len(df.PatientId)

True

The data has patients with more than one appointment. Let's check how many PatientId are duplicated

In [10]:
df.PatientId.duplicated().sum()

26119

I am going to check the mean, min and max appointment quantity by patient

In [54]:
df.groupby(['PatientId']).count().AppointmentID.describe(percentiles=[.25, .5, .75, .85, .90, .95, .98, .99, 1])

count    45840.000000
mean         1.569786
std          1.208899
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
85%          2.000000
90%          3.000000
95%          4.000000
98%          5.000000
99%          6.000000
100%        30.000000
max         30.000000
Name: AppointmentID, dtype: float64

The mean is 1.56 but Seems that some patients has 30 appointments. Let's  check these patients

In [51]:
index = df.groupby(['PatientId']).count().query('AppointmentID == 30').index.tolist()
index

[1484143378533.0]

Just one patient has 30 appointments

In [52]:
df.query('PatientId == {}'.format(index))

PatientId  AppointmentID Gender        ScheduledDay AppointmentDay  \
2304    1.484143e+12        5573128      F 2016-04-12 11:56:51     2016-04-29   
13840   1.484143e+12        5640785      F 2016-04-29 11:24:43     2016-05-03   
13841   1.484143e+12        5669806      F 2016-05-06 11:43:15     2016-05-10   
13850   1.484143e+12        5653073      F 2016-05-03 11:11:49     2016-05-05   
13851   1.484143e+12        5680145      F 2016-05-10 11:10:19     2016-05-12   
21811   1.484143e+12        5624634      F 2016-04-26 16:36:37     2016-05-02   
21812   1.484143e+12        5649276      F 2016-05-02 18:56:40     2016-05-09   
21813   1.484143e+12        5682707      F 2016-05-10 18:22:16     2016-05-16   
21814   1.484143e+12        5734852      F 2016-05-24 16:18:11     2016-05-30   
21865   1.484143e+12        5624674      F 2016-04-26 16:41:54     2016-05-05   
21866   1.484143e+12        5649306      F 2016-05-02 19:00:08     2016-05-12   
21867   1.484143e+12        5682734      F 2016-05-10 18:25:26     2016-05-19   
21868   1.484143e+12        5682715      F 2016-05-10 18:23:07     2016-05-17   
21869   1.484143e+12        5728785      F 2016-05-20 18:35:35     2016-05-24   
21870   1.484143e+12        5734864      F 2016-05-24 16:19:26     2016-05-31   
21871   1.484143e+12        5624644      F 2016-04-26 16:38:19     2016-05-03   
21872   1.484143e+12        5649283      F 2016-05-02 18:57:31     2016-05-10   
21896   1.484143e+12        5624726      F 2016-04-26 16:48:57     2016-05-06   
21897   1.484143e+12        5649316      F 2016-05-02 19:01:32     2016-05-13   
21898   1.484143e+12        5682745      F 2016-05-10 18:26:40     2016-05-20   
21924   1.484143e+12        5682727      F 2016-05-10 18:24:33     2016-05-18   
21925   1.484143e+12        5728798      F 2016-05-20 18:37:05     2016-05-25   
21930   1.484143e+12        5624663      F 2016-04-26 16:40:50     2016-05-04   
21931   1.484143e+12        5649297      F 2016-05-02 18:59:07     2016-05-11   
104461  1.484143e+12        5734886      F 2016-05-24 16:21:18     2016-06-01   
104473  1.484143e+12        5759044      F 2016-06-01 11:40:44     2016-06-03   
104481  1.484143e+12        5771028      F 2016-06-03 11:23:03     2016-06-07   
104482  1.484143e+12        5752346      F 2016-05-31 11:35:42     2016-06-02   
104495  1.484143e+12        5765213      F 2016-06-02 11:55:25     2016-06-06   
106964  1.484143e+12        5747752      F 2016-05-30 16:17:10     2016-06-02   

        Age   Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
2304     56  GRANDE VITÓRIA            0             1         0           0   
13840    56  GRANDE VITÓRIA            0             1         0           0   
13841    56  GRANDE VITÓRIA            0             1         0           0   
13850    56  GRANDE VITÓRIA            0             1         0           0   
13851    56  GRANDE VITÓRIA            0             1         0           0   
21811    56  GRANDE VITÓRIA            0             1         0           0   
21812    56  GRANDE VITÓRIA            0             1         0           0   
21813    56  GRANDE VITÓRIA            0             1         0           0   
21814    56  GRANDE VITÓRIA            0             1         0           0   
21865    56  GRANDE VITÓRIA            0             1         0           0   
21866    56  GRANDE VITÓRIA            0             1         0           0   
21867    56  GRANDE VITÓRIA            0             1         0           0   
21868    56  GRANDE VITÓRIA            0             1         0           0   
21869    56  GRANDE VITÓRIA            0             1         0           0   
21870    56  GRANDE VITÓRIA            0             1         0           0   
21871    56  GRANDE VITÓRIA            0             1         0           0   
21872    56  GRANDE VITÓRIA            0             1         0           0   
21896    56  GRANDE VITÓRIA            0             1     

<a id='eda'></a>
## Exploratory Data Analysis

> **Tip**: Now that you've trimmed and cleaned your data, you're ready to move on to exploration. Compute statistics and create visualizations with the goal of addressing the research questions that you posed in the Introduction section. It is recommended that you be systematic with your approach. Look at one variable at a time, and then follow it up by looking at relationships between variables.

### Research Question 1 (Replace this header name!)

In [ ]:
# Use this, and more code cells, to explore your data. Don't forget to add
#   Markdown cells to document your observations and findings.


### Research Question 2  (Replace this header name!)

In [ ]:
# Continue to explore the data to address your additional research
#   questions. Add more headers as needed if you have more questions to
#   investigate.


<a id='conclusions'></a>
## Conclusions

> **Tip**: Finally, summarize your findings and the results that have been performed. Make sure that you are clear with regards to the limitations of your exploration. If you haven't done any statistical tests, do not imply any statistical conclusions. And make sure you avoid implying causation from correlation!

> **Tip**: Once you are satisfied with your work, you should save a copy of the report in HTML or PDF form via the **File** > **Download as** submenu. Before exporting your report, check over it to make sure that the flow of the report is complete. You should probably remove all of the "Tip" quotes like this one so that the presentation is as tidy as possible. Congratulations!