# Brazil - No Show Appointment - Deu Migué <a id='topo'></a>

## Table of Contents
<ul>
<li>
    <a href="#intro">Introduction</a>
    <ul>
        <li><a href="#objective">Objective</a></li>
        <li><a href="#columns">Columns descriptions and insights</a></li>
    </ul>
</li>
<li>
    <a href="#wrangling">Data Wrangling</a>
    <ul>
        <li><a href="#general">General Properties</a></li>
        <li><a href="#snake">Change columns to snake case</a></li>
        <li><a href="#check_unique">Check unique values</a></li>
        <li><a href="#convert_date">Convert to datetime</a></li>
        <li><a href="#check_date">Check the date fields</a></li>
        <ul>
            <li><a href="#check_schecule_appointment">Check if ScheduledDay > AppointmentDay</a></li>
            <li><a href="#clean_schedule">Clean ScheduledDay >= AppointmentDay</a></li>
        </ul>
        <li><a href="#check_appointment">Check AppointmentID</a></li>
        <li><a href="#check_patient">Check PatientId</a></li>
        <li><a href="#no_show">Change no show column</a></li>
        <li><a href="#check_age">Check age</a></li>
    </ul>
</li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

## Introduction <a id='intro'></a>

This dataset collects information from 100k medical appointments in Brazil and is focused on the question of whether or not patients show up for their appointment. A number of characteristics about the patient are included in each row.

You can download the dataset [here](https://d17h27t6h515a5.cloudfront.net/topher/2017/October/59dd2e9a_noshowappointments-kagglev2-may-2016/noshowappointments-kagglev2-may-2016.csv). Put the file in same directory of this file and rename it to 'brasil_migue.csv'.

### Objective <a id='objective'></a>
The objective of this analysis is to discover some correlations about the reasons of patients that not show up in a scheduled appointment.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('brasil_migue.csv')

In [3]:
df.head(4)

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No

## Columns descriptions and insights <a id='columns'></a>

The columns that is not listed below are considered self explained.
- **Scholarship** - Indicates whether or not the patient is enrolled in Brasilian welfare program Bolsa Família. 
    - Could indicate the real scholarship of the patient. The information if the patition is in the welfare could be another column.
    
- **ScheduledDay** - The day that the patient set up their appointment. 
    - In the first lines listed above is possible to see some problems in this data, some dates are the same or after the appointment day. The same day is a problem because in brazilian public hospiltals an appointment is scheduled only months before. This data does not seem truthful.

- **Neighbourhood** - The place where the hospital is located and not where the patient lives.
    - A data set with informations about the region could be useful. Only the the name of the place, where the hospital is located, become diffcult to link the place with the reason that the patient does not show up. The location where the patient live could be useful because some hospitals receive patients from another cities.

- **Handcap** - I am considering that the handicap means people with disabilities.

- **No-show** - Yes if the patient does not show up.
    - I could invert the 'yes' data value mean to when the patient showed up. The column name could be showed up in this case. This could avoid misunderstood.
    
- **SMS_received** - If the patient received a sms remembering about the appointment.
    - I have doubts about if this data is relevant. There is some reasons about my doubts that I am going to try to explain below:
        - This system of reminder is not common in Brazil
        - Some patients are enrolled in the welfare program Bolsa Família. Most certain that they do not have cellphones. This can be cheked more later in the data analysis.
        - The data do not explain when the sms was received.

> **Note**: The insights above are only my first impressions about the data. I am going to do a more profund analysis later in this document.  

## Data Wrangling <a id='wrangling'/>

### General Properties <a id='general'></a>
Display all the info about the data. <a href='#topo'>Top</a>

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
PatientId         110527 non-null float64
AppointmentID     110527 non-null int64
Gender            110527 non-null object
ScheduledDay      110527 non-null object
AppointmentDay    110527 non-null object
Age               110527 non-null int64
Neighbourhood     110527 non-null object
Scholarship       110527 non-null int64
Hipertension      110527 non-null int64
Diabetes          110527 non-null int64
Alcoholism        110527 non-null int64
Handcap           110527 non-null int64
SMS_received      110527 non-null int64
No-show           110527 non-null object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


There is no mising values in the data frame. Let's check if has duplicates values

In [5]:
sum(df.duplicated())

0

### Change columns to snake case <a id="snake"/>
I am going to change the columns to snake case to become more easy to explore the data set. <a href='#topo'>Top</a>

In [6]:
import data_frame_helper

In [7]:
data_frame_helper.columns_to_snake_case(df).columns

Index(['patient_id', 'appointment_id', 'gender', 'scheduled_day',
       'appointment_day', 'age', 'neighbourhood', 'scholarship',
       'hipertension', 'diabetes', 'alcoholism', 'handcap', 'sms_received',
       'no-show'],
      dtype='object')

In [8]:
df.columns = df.columns.str.replace('-', '_')
df.columns

Index(['patient_id', 'appointment_id', 'gender', 'scheduled_day',
       'appointment_day', 'age', 'neighbourhood', 'scholarship',
       'hipertension', 'diabetes', 'alcoholism', 'handcap', 'sms_received',
       'no_show'],
      dtype='object')

### Check unique values <a id='check_unique'></a>
The columns below should jsut have two possible values each. Let's check if is allright with the unique function. <a href='#topo'>Top</a>

In [9]:
df.gender.unique()

array(['F', 'M'], dtype=object)

In [10]:
df.scholarship.unique()

array([0, 1], dtype=int64)

In [11]:
df.hipertension.unique()

array([1, 0], dtype=int64)

In [12]:
df.diabetes.unique()

array([0, 1], dtype=int64)

In [13]:
df.alcoholism.unique()

array([0, 1], dtype=int64)

In [14]:
df.handcap.unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [15]:
df.sms_received.unique()

array([0, 1], dtype=int64)

In [16]:
df.no_show.unique()

array(['No', 'Yes'], dtype=object)

According with the data set documentation, the Handcap column should be true or false. Futhermore, I am going to check if this data has some correlation with the patients that do not show up.

### Convert to datetime <a id='convert_date'></a>
First, let's convert to datetime the scheduled day and appointment day column. <a href='#topo'>Top</a>

In [17]:
df.scheduled_day = pd.to_datetime(df.scheduled_day)
df.appointment_day = pd.to_datetime(df.appointment_day)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
patient_id         110527 non-null float64
appointment_id     110527 non-null int64
gender             110527 non-null object
scheduled_day      110527 non-null datetime64[ns]
appointment_day    110527 non-null datetime64[ns]
age                110527 non-null int64
neighbourhood      110527 non-null object
scholarship        110527 non-null int64
hipertension       110527 non-null int64
diabetes           110527 non-null int64
alcoholism         110527 non-null int64
handcap            110527 non-null int64
sms_received       110527 non-null int64
no_show            110527 non-null object
dtypes: datetime64[ns](2), float64(1), int64(8), object(3)
memory usage: 11.8+ MB


### Check the date fields <a id='check_date'></a>
How we see before, the data set has some inconsistent data in the date fields, Scheduled Day and Appointment Day. Let's check with more details in the steps below. <a href='#topo'>Top</a>

#### Check if ScheduledDay > AppointmentDay <a id='check_schecule_appointment'></a>
I want to check how many Scheduled days are after the AppointmentDay. <a href='#topo'>Top</a>

In [19]:
df.query('scheduled_day > appointment_day')

patient_id  appointment_id gender       scheduled_day  \
0       2.987250e+13         5642903      F 2016-04-29 18:38:08   
1       5.589978e+14         5642503      M 2016-04-29 16:08:27   
2       4.262962e+12         5642549      F 2016-04-29 16:19:04   
3       8.679512e+11         5642828      F 2016-04-29 17:29:31   
4       8.841186e+12         5642494      F 2016-04-29 16:07:23   
8       5.639473e+13         5638447      F 2016-04-29 08:02:16   
19      7.223289e+12         5640433      F 2016-04-29 10:43:14   
24      8.734858e+12         5641780      F 2016-04-29 14:19:19   
26      2.578785e+10         5641781      F 2016-04-29 14:19:42   
28      5.926172e+12         5642400      M 2016-04-29 15:48:02   
29      1.225776e+12         5642186      F 2016-04-29 15:16:29   
32      5.288356e+13         5637908      M 2016-04-29 07:30:27   
34      1.999976e+13         5637963      F 2016-04-29 07:34:30   
35      7.816264e+13         5637968      M 2016-04-29 07:34:42   
36      7.298459e+13         5637975      F 2016-04-29 07:35:19   
37      1.578132e+12         5637986      F 2016-04-29 07:35:56   
39      1.455623e+13         5639644      F 2016-04-29 09:21:13   
43      7.155896e+13         5641620      F 2016-04-29 14:02:16   
53      4.438587e+14         5637909      M 2016-04-29 07:30:31   
54      3.371889e+12         5638164      F 2016-04-29 07:46:08   
55      4.179932e+13         5638018      M 2016-04-29 07:37:45   
57      3.996740e+12         5638466      M 2016-04-29 08:03:51   
58      4.487944e+10         5638235      M 2016-04-29 07:50:15   
59      7.184428e+13         5638545      F 2016-04-29 08:08:43   
66      9.784893e+14         5638604      M 2016-04-29 08:12:27   
67      8.647128e+13         5639264      F 2016-04-29 08:53:02   
72      7.746486e+12         5638014      F 2016-04-29 07:37:37   
77      5.753721e+12         5642767      F 2016-04-29 17:06:27   
82      1.827125e+11         5638939      M 2016-04-29 08:36:19   
83      2.274979e+11         5637742      M 2016-04-29 07:20:46   
...              ...             ...    ...                 ...   
110475  2.123885e+14         5779726      F 2016-06-07 07:14:07   
110483  1.642781e+12         5769404      F 2016-06-03 08:47:58   
110486  3.184153e+14         5788099      F 2016-06-08 11:14:23   
110487  1.891645e+12         5786423      M 2016-06-08 08:24:51   
110488  7.935892e+14         5760379      M 2016-06-01 14:47:12   
110489  7.874370e+14         5788924      F 2016-06-08 13:54:16   
110490  3.252624e+14         5787975      M 2016-06-08 10:55:45   
110491  7.565622e+11         5787950      F 2016-06-08 10:52:27   
110492  6.456342e+14         5786741      M 2016-06-08 08:50:19   
110493  1.712135e+11         5788054      M 2016-06-08 11:06:40   
110495  7.499489e+12         5759838      M 2016-06-01 13:49:47   
110497  7.935892e+14         5757745      M 2016-06-01 09:46:33   
110498  9.433654e+13         5787655      F 2016-06-08 10:21:14   
110499  8.219692e+14         5757697      F 2016-06-01 09:42:56   
110500  4.434384e+14         5787233      F 2016-06-08 09:35:13   
110501  4.544252e+11         5758133      M 2016-06-01 10:19:12   
110502  7.316229e+14         5787937      F 2016-06-08 10:50:42   
110503  2.362182e+13         5759473      F 2016-06-01 13:00:36   
110504  9.947983e+12         5788052      F 2016-06-08 11:06:21   
110505  5.667344e+13         5758455      F 2016-06-01 10:45:50   
110506  8.973883e+11         5758779      M 2016-06-01 11:09:20   
110507  4.769462e+14         5786918      F 2016-06-08 09:04:18   
110508  9.433654e+13         5757656      F 2016-06-01 09:41:00   
110509  4.952968e+14         5786750      M 2016-06-08 08:50:51   
110510  2.362182e+13         5757587      F 2016-06-01 09:35:48   
110511  8.235996e+11         5786742      F 2016-06-08 08:50:20   
110512  9.876246e+13         5786368      F 2016-06-08 08:20:01   
110513  8.674778e+13         5785964      M 2016-06-08 07

In [20]:
sum(df.scheduled_day > df.appointment_day)

38568

In [21]:
sum(df.scheduled_day == df.appointment_day)

0

I want to check if some patient in the results above received a sms

In [22]:
df.query('scheduled_day > appointment_day and sms_received == 1').sms_received.count()

0

I am going to check if Appointment Day column has some value with time

In [23]:
sum(df.appointment_day.apply(lambda x: x.hour + x.minute + x.second + x.microsecond))

0

The column Appointment Day does not have time. I am going to check if has scheduled day value after the appointment day

In [24]:
different_day_array = []
for index, row in df.query('scheduled_day > appointment_day').iterrows():
    if row['scheduled_day'].day != row['appointment_day'].day:
        different_day_array.append(index)

In [25]:
df.loc[different_day_array].head()

patient_id  appointment_id gender       scheduled_day  \
27033  7.839273e+12         5679978      M 2016-05-10 10:51:53   
55226  7.896294e+12         5715660      F 2016-05-18 14:50:41   
64175  2.425226e+13         5664962      F 2016-05-05 13:43:58   
71533  9.982316e+14         5686628      F 2016-05-11 13:49:20   
72362  3.787482e+12         5655637      M 2016-05-04 06:50:57   

      appointment_day  age  neighbourhood  scholarship  hipertension  \
27033      2016-05-09   38    RESISTÊNCIA            0             0   
55226      2016-05-17   19  SANTO ANTÔNIO            0             0   
64175      2016-05-04   22     CONSOLAÇÃO            0             0   
71533      2016-05-05   81  SANTO ANTÔNIO            0             0   
72362      2016-05-03    7     TABUAZEIRO            0             0   

       diabetes  alcoholism  handcap  sms_received no_show  
27033         0           0        1             0     Yes  
55226         0           0        1             0     Yes  
64175         0           0        0             0     Yes  
71533         0           0        0             0     Yes  
72362         0           0        0             0     Yes

The dataset has values with scheduled day after the appointment day. I am going to remove these data.
The appointment values does not have time, so the appointment date in the same day of scheduled date could be after the schedule. But in Brazil there is no possible that the scheduled and appointment day be the same, so I am going to remove the rows that contains schedule equal or after the appointment.

#### Clean ScheduledDay >= AppointmentDay <a id='clean_schedule'></a>
<a href='#topo'>Top</a>

In [26]:
df = df.query('scheduled_day < appointment_day')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71959 entries, 5 to 110526
Data columns (total 14 columns):
patient_id         71959 non-null float64
appointment_id     71959 non-null int64
gender             71959 non-null object
scheduled_day      71959 non-null datetime64[ns]
appointment_day    71959 non-null datetime64[ns]
age                71959 non-null int64
neighbourhood      71959 non-null object
scholarship        71959 non-null int64
hipertension       71959 non-null int64
diabetes           71959 non-null int64
alcoholism         71959 non-null int64
handcap            71959 non-null int64
sms_received       71959 non-null int64
no_show            71959 non-null object
dtypes: datetime64[ns](2), float64(1), int64(8), object(3)
memory usage: 8.2+ MB


### Check AppointmentID <a id='check_appointment'></a>
Beforehand, I am goind to check if the data has Appointment id duplicated. <a href='#topo'>Top</a>

In [28]:
df.appointment_id.duplicated().sum()

0

### Check PatientId <a id='check_patient'></a>
Maybe the patient can have more than one appointment. Let's check. <a href='#topo'>Top</a>

In [29]:
# Must be true to has more than one appointment
len(df.patient_id.unique()) != len(df.patient_id)

True

The data has patients with more than one appointment. Let's check how many PatientId are duplicated

In [30]:
df.patient_id.duplicated().sum()

26119

I am going to check the mean, min and max appointment quantity by patient

In [31]:
df.groupby(['patient_id']).count().appointment_id.describe(percentiles=[.25, .5, .75, .85, .90, .95, .98, .99, 1])

count    45840.000000
mean         1.569786
std          1.208899
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
85%          2.000000
90%          3.000000
95%          4.000000
98%          5.000000
99%          6.000000
100%        30.000000
max         30.000000
Name: appointment_id, dtype: float64

The mean is 1.56 but Seems that some patients has 30 appointments. Let's  check these patients

In [32]:
index = df.groupby(['patient_id']).count().query('appointment_id == 30').index.tolist()
index

[1484143378533.0]

Just one patient has 30 appointments

In [33]:
df.query('patient_id == {}'.format(index))

patient_id  appointment_id gender       scheduled_day  \
2304    1.484143e+12         5573128      F 2016-04-12 11:56:51   
13840   1.484143e+12         5640785      F 2016-04-29 11:24:43   
13841   1.484143e+12         5669806      F 2016-05-06 11:43:15   
13850   1.484143e+12         5653073      F 2016-05-03 11:11:49   
13851   1.484143e+12         5680145      F 2016-05-10 11:10:19   
21811   1.484143e+12         5624634      F 2016-04-26 16:36:37   
21812   1.484143e+12         5649276      F 2016-05-02 18:56:40   
21813   1.484143e+12         5682707      F 2016-05-10 18:22:16   
21814   1.484143e+12         5734852      F 2016-05-24 16:18:11   
21865   1.484143e+12         5624674      F 2016-04-26 16:41:54   
21866   1.484143e+12         5649306      F 2016-05-02 19:00:08   
21867   1.484143e+12         5682734      F 2016-05-10 18:25:26   
21868   1.484143e+12         5682715      F 2016-05-10 18:23:07   
21869   1.484143e+12         5728785      F 2016-05-20 18:35:35   
21870   1.484143e+12         5734864      F 2016-05-24 16:19:26   
21871   1.484143e+12         5624644      F 2016-04-26 16:38:19   
21872   1.484143e+12         5649283      F 2016-05-02 18:57:31   
21896   1.484143e+12         5624726      F 2016-04-26 16:48:57   
21897   1.484143e+12         5649316      F 2016-05-02 19:01:32   
21898   1.484143e+12         5682745      F 2016-05-10 18:26:40   
21924   1.484143e+12         5682727      F 2016-05-10 18:24:33   
21925   1.484143e+12         5728798      F 2016-05-20 18:37:05   
21930   1.484143e+12         5624663      F 2016-04-26 16:40:50   
21931   1.484143e+12         5649297      F 2016-05-02 18:59:07   
104461  1.484143e+12         5734886      F 2016-05-24 16:21:18   
104473  1.484143e+12         5759044      F 2016-06-01 11:40:44   
104481  1.484143e+12         5771028      F 2016-06-03 11:23:03   
104482  1.484143e+12         5752346      F 2016-05-31 11:35:42   
104495  1.484143e+12         5765213      F 2016-06-02 11:55:25   
106964  1.484143e+12         5747752      F 2016-05-30 16:17:10   

       appointment_day  age   neighbourhood  scholarship  hipertension  \
2304        2016-04-29   56  GRANDE VITÓRIA            0             1   
13840       2016-05-03   56  GRANDE VITÓRIA            0             1   
13841       2016-05-10   56  GRANDE VITÓRIA            0             1   
13850       2016-05-05   56  GRANDE VITÓRIA            0             1   
13851       2016-05-12   56  GRANDE VITÓRIA            0             1   
21811       2016-05-02   56  GRANDE VITÓRIA            0             1   
21812       2016-05-09   56  GRANDE VITÓRIA            0             1   
21813       2016-05-16   56  GRANDE VITÓRIA            0             1   
21814       2016-05-30   56  GRANDE VITÓRIA            0             1   
21865       2016-05-05   56  GRANDE VITÓRIA            0             1   
21866       2016-05-12   56  GRANDE VITÓRIA            0             1   
21867       2016-05-19   56  GRANDE VITÓRIA            0             1   
21868       2016-05-17   56  GRANDE VITÓRIA            0             1   
21869       2016-05-24   56  GRANDE VITÓRIA            0             1   
21870       2016-05-31   56  GRANDE VITÓRIA            0             1   
21871       2016-05-03   56  GRANDE VITÓRIA            0             1   
21872       2016-05-10   56  GRANDE VITÓRIA            0             1   
21896       2016-05-06   56  GRANDE VITÓRIA            0             1   
21897       2016-05-13   56  GRANDE VITÓRIA            0             1   
21898       2016-05-20   56  GRANDE VITÓRIA            0             1   
21924       2016-05-18   56  GRANDE VITÓRIA            0             1   
21925       2016-05-25   56  GRANDE VITÓRIA            0             1   
21930       2016-05-04   56  GRANDE VITÓRIA            0             1   
21931       2016-05-11   56  GRANDE VITÓRIA            0             1   
104461      2016-06-01   56  GRANDE VITÓRIA            0             1   
104473  

### Change no show column <a id='no_show'/>
In the column no show, the values Yes means that the patient no showed up. Let's change the values to means that 1 is when the patient showed up and 0 not. I am going to change the column name to showed up to avoid misunderstood. <a href='#topo'>Top</a>

In [34]:
import brasil_migue as brm

In [35]:
df.no_show.head(4)

5     No
6    Yes
7    Yes
9     No
Name: no_show, dtype: object

In [36]:
brm.invert_no_show_values(df).showed_up.head(4)

5    1
6    0
7    0
9    1
Name: showed_up, dtype: int64

In [37]:
df.columns

Index(['patient_id', 'appointment_id', 'gender', 'scheduled_day',
       'appointment_day', 'age', 'neighbourhood', 'scholarship',
       'hipertension', 'diabetes', 'alcoholism', 'handcap', 'sms_received',
       'showed_up'],
      dtype='object')

### Check age <a id='check_age'/>
I am going to check the column age. <a href='#topo'>Top</a>

In [49]:
df.age.describe()

count    71959.000000
mean        38.502564
std         22.925421
min          0.000000
25%         19.000000
50%         39.000000
75%         57.000000
max        115.000000
Name: age, dtype: float64

In [48]:
df.age.value_counts()

0      2131
52     1144
53     1132
56     1132
57     1126
50     1121
54     1109
49     1107
1      1084
59     1081
51     1073
36     1040
58     1038
55     1027
30     1023
39     1018
60     1006
32     1004
37      997
38      995
34      987
33      976
6       962
19      960
47      956
21      954
61      954
44      950
31      944
28      944
       ... 
71      473
74      450
72      428
78      405
75      401
76      379
77      378
80      358
81      291
82      258
79      240
83      210
84      201
85      181
86      169
87      129
89      123
88       81
90       80
92       57
91       47
93       34
94       27
95       12
97        6
98        5
96        5
100       4
115       4
102       1
Name: age, Length: 102, dtype: int64

As we can see above, there is some values with age == 0. I can imagine that is a child with just months of live. I am going to check if data is ok for this case.

In [50]:
df.query('age == 0')

patient_id  appointment_id gender       scheduled_day  \
63      2.366233e+14         5628286      M 2016-04-27 10:46:12   
64      1.885174e+14         5616082      M 2016-04-25 13:28:21   
65      2.718818e+14         5628321      M 2016-04-27 10:48:50   
104     3.326985e+12         5632495      F 2016-04-28 08:04:48   
132     8.468587e+14         5560742      M 2016-04-08 09:29:23   
193     2.379698e+11         5532452      F 2016-03-31 11:14:57   
194     4.442538e+11         5539566      M 2016-04-01 15:17:10   
256     8.599713e+10         5629906      F 2016-04-27 14:19:02   
358     7.349270e+14         5531831      F 2016-03-31 10:07:18   
359     7.975283e+11         5551583      M 2016-04-06 14:20:30   
366     3.499167e+14         5531933      F 2016-03-31 10:14:54   
377     9.123627e+11         5522585      M 2016-03-29 14:39:32   
434     9.625417e+14         5533985      F 2016-03-31 15:01:12   
524     5.815365e+13         5488633      M 2016-03-18 10:35:28   
525     4.239228e+13         5537936      F 2016-04-01 10:53:45   
565     5.569896e+14         5591488      F 2016-04-15 17:39:38   
809     7.872547e+13         5552928      F 2016-04-06 18:05:31   
888     2.314344e+11         5515907      M 2016-03-28 13:45:13   
1042    8.191675e+13         5590725      M 2016-04-15 14:48:44   
1081    2.768224e+13         5621425      F 2016-04-26 10:16:29   
1086    6.852261e+13         5598603      M 2016-04-19 07:46:21   
1087    6.852261e+13         5598599      M 2016-04-19 07:46:11   
1145    5.853129e+11         5623706      F 2016-04-26 14:30:10   
1165    6.669153e+11         5633961      M 2016-04-28 10:08:40   
1201    5.939342e+13         5533154      M 2016-03-31 13:25:20   
1204    7.681658e+13         5533283      F 2016-03-31 13:39:34   
1206    1.189550e+12         5561246      M 2016-04-08 10:19:33   
1208    9.413184e+12         5522193      M 2016-03-29 13:50:39   
1216    7.849416e+12         5515938      F 2016-03-28 13:48:49   
1218    7.186678e+14         5515946      F 2016-03-28 13:49:42   
...              ...             ...    ...                 ...   
108996  9.721978e+14         5761215      M 2016-06-01 16:42:47   
109002  9.368361e+12         5762903      F 2016-06-02 08:20:23   
109344  1.754176e+13         5681646      M 2016-05-10 14:50:13   
109346  6.577378e+14         5772711      F 2016-06-03 16:06:56   
109629  3.689222e+13         5660428      F 2016-05-04 16:30:06   
109633  3.689222e+13         5660427      F 2016-05-04 16:30:06   
109646  5.941811e+13         5659194      M 2016-05-04 13:21:32   
109647  5.635258e+13         5691391      M 2016-05-12 12:35:04   
109649  5.941811e+13         5659193      M 2016-05-04 13:21:32   
109650  5.635258e+13         5691390      M 2016-05-12 12:35:04   
109830  6.931429e+11         5739239      F 2016-05-25 13:07:38   
109847  9.174483e+11         5685977      M 2016-05-11 11:33:48   
109848  5.853540e+12         5707361      M 2016-05-17 09:32:32   
109852  1.663316e+13         5731578      F 2016-05-24 10:14:26   
110231  1.731548e+14         5634706      M 2016-04-28 11:32:00   
110235  3.279373e+14         5634274      M 2016-04-28 10:40:49   
110236  1.174717e+13         5669996      M 2016-05-06 12:31:22   
110299  5.944513e+10         5746323      F 2016-05-30 13:47:40   
110313  8.535734e+12         5600209      F 2016-04-19 10:09:05   
110319  4.524190e+11         5640301      F 2016-04-29 10:28:16   
110320  3.459268e+13         5675103      M 2016-05-09 13:02:20   
110321  1.388630e+11         5338643      M 2016-02-11 16:14:32   
110331  2.739486e+13         5392089      F 2016-02-24 15:33:08   
110335  3.747953e+11         5338761      M 2016-02-11 16:39:26   
110339  3.731746e+12         5584042      M 2016-04-14 13:01:21   
110341  4.696832e+12         5713894      M 2016-05-18 10:55:00   
110342  3.147163e+11         5776749      M 2016-06-06 11:48:00   
110343  1.759439e+12         5690822      F 2016-05-12 10

Seems alright. Let's check the ages avaliable in the data set.

In [55]:
ages = df.age.unique()
ages.sort()
ages

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98, 100, 102, 115], dtype=int64)

We have all the ages, with no interruption, until 98 years old.

### Check neighbourhood <a id='check_nei'/>
 The column neighbourhood could have values duplicated with different cases. Let's check it. <a href='#topo'>Top</a>

In [65]:
df.neighbourhood.unique()

array(['REPÚBLICA', 'GOIABEIRAS', 'CONQUISTA', 'NOVA PALESTINA',
       'SÃO CRISTÓVÃO', 'TABUAZEIRO', 'MARUÍPE', 'GRANDE VITÓRIA',
       'SÃO BENEDITO', 'ILHA DAS CAIEIRAS', 'JARDIM DA PENHA',
       'SANTO ANDRÉ', 'SOLON BORGES', 'BONFIM', 'MARIA ORTIZ', 'JABOUR',
       'ANTÔNIO HONÓRIO', 'RESISTÊNCIA', 'ILHA DE SANTA MARIA',
       'JUCUTUQUARA', 'MÁRIO CYPRESTE', 'SANTO ANTÔNIO', 'BELA VISTA',
       'PRAIA DO SUÁ', 'DA PENHA', 'ITARARÉ', 'ANDORINHAS', 'SÃO PEDRO',
       'SÃO JOSÉ', 'REDENÇÃO', 'SANTOS DUMONT', 'CARATOÍRA',
       'ARIOVALDO FAVALESSA', 'UNIVERSITÁRIO', 'SANTA MARTHA',
       'JOANA D´ARC', 'CONSOLAÇÃO', 'JARDIM CAMBURI', 'BOA VISTA',
       'MORADA DE CAMBURI', 'CENTRO', 'PARQUE MOSCOSO', 'SANTA CLARA',
       'DO MOSCOSO', 'SANTA LUÍZA', 'PRAIA DO CANTO', 'SANTA LÚCIA',
       'BARRO VERMELHO', 'BENTO FERREIRA', 'ESTRELINHA', 'FORTE SÃO JOÃO',
       'FONTE GRANDE', 'ENSEADA DO SUÁ', 'SANTOS REIS', 'PIEDADE',
       'JESUS DE NAZARETH', 'SANTA TEREZA', 'GURIGI

<a id='eda'></a>
## Exploratory Data Analysis

> **Tip**: Now that you've trimmed and cleaned your data, you're ready to move on to exploration. Compute statistics and create visualizations with the goal of addressing the research questions that you posed in the Introduction section. It is recommended that you be systematic with your approach. Look at one variable at a time, and then follow it up by looking at relationships between variables.

### Research Question 1 (Replace this header name!)

In [ ]:
# Use this, and more code cells, to explore your data. Don't forget to add
#   Markdown cells to document your observations and findings.


### Research Question 2  (Replace this header name!)

In [ ]:
# Continue to explore the data to address your additional research
#   questions. Add more headers as needed if you have more questions to
#   investigate.


<a id='conclusions'></a>
## Conclusions

> **Tip**: Finally, summarize your findings and the results that have been performed. Make sure that you are clear with regards to the limitations of your exploration. If you haven't done any statistical tests, do not imply any statistical conclusions. And make sure you avoid implying causation from correlation!

> **Tip**: Once you are satisfied with your work, you should save a copy of the report in HTML or PDF form via the **File** > **Download as** submenu. Before exporting your report, check over it to make sure that the flow of the report is complete. You should probably remove all of the "Tip" quotes like this one so that the presentation is as tidy as possible. Congratulations!